version: '3.1'
services:
    khoy-total:
        build: .
        container_name: khoytotal
        ports:
            - "5000:5000"
        volumes:
            - .:/code
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        environment:
            FLASK_ENV: development
